// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    EliAim: typeof import('@element-plus/icons-vue/dist/lib/aim.vue')['default']
    EliArrowDownBold: typeof import('@element-plus/icons-vue/dist/lib/arrow-down-bold.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    EliExpand: typeof import('@element-plus/icons-vue/dist/lib/expand.vue')['default']
    ElInput: typeof import('element-plus/es')['ElInput']
    EliRefresh: typeof import('@element-plus/icons-vue/dist/lib/refresh.vue')['default']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ICustomCloseFullscreen: typeof import('~icons/custom/close-fullscreen')['default']
    ICustomFullscreen: typeof import('~icons/custom/fullscreen')['default']
    TestCom: typeof import('./src/components/TestCom/index.vue')['default']
    UForm: typeof import('./src/components/UForm/index.vue')['default']
    UTable: typeof import('./src/components/UTable/index.vue')['default']
  }
}

export { }
